package com.xyratex.label.apps.gui.components;

/*
 * OverallJPanel.java
 *
 * Created on 17 November 2008, 15:42
 */



/**
 *
 * @author  rdavis
 */
public class XyOverallJPanel extends javax.swing.JPanel {

    /** Creates new form OverallJPanel */
    public XyOverallJPanel() {
        initComponents();
    }
    
    public XyLabelTemplateImageJPanel getLabelTemplateImageJPanel()
    {
        return xyLabelTemplateImageJPanel1;
    }
    
    public XyLoadLabelTemplateJPanel getLoadLabelTemplateJPanel()
    {
        return xyLoadLabelTemplateJPanel1;
    }
    
    public XyOffsettingJPanel getOffsettingJPanel()
    {
        return xyOffsettingJPanel1;
    }
    
    public XyPrinterControlJPanel getPrinterControlJPanel()
    {
        return xyPrinterControlJPanel1;
    }
            
    public XyOLPRecallPrintedLabelJPanel getRecallPrintedLabelJPanel()
    {
      return xyOLPRecallPrintedLabelJPanel1;
    }
    
    public XyOLPStoreLabelJPanel1 getStoreLabelJPanel()
    {
      return xyOLPStoreLabelJPanel11;
    }
    
            
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xyOLPLaunchSettingsJPanel1 = new com.xyratex.label.apps.gui.components.XyOLPLaunchSettingsJPanel();
        xyLoadLabelTemplateJPanel1 = new com.xyratex.label.apps.gui.components.XyLoadLabelTemplateJPanel();
        xyOLPRecallPrintedLabelJPanel1 = new com.xyratex.label.apps.gui.components.XyOLPRecallPrintedLabelJPanel();
        xyOLPStoreLabelJPanel11 = new com.xyratex.label.apps.gui.components.XyOLPStoreLabelJPanel1();
        xyOffsettingJPanel1 = new com.xyratex.label.apps.gui.components.XyOffsettingJPanel();
        xyPrinterControlJPanel1 = new com.xyratex.label.apps.gui.components.XyPrinterControlJPanel();
        xyLabelTemplateImageJPanel1 = new com.xyratex.label.apps.gui.components.XyLabelTemplateImageJPanel();

        javax.swing.GroupLayout xyLabelTemplateImageJPanel1Layout = new javax.swing.GroupLayout(xyLabelTemplateImageJPanel1);
        xyLabelTemplateImageJPanel1.setLayout(xyLabelTemplateImageJPanel1Layout);
        xyLabelTemplateImageJPanel1Layout.setHorizontalGroup(
            xyLabelTemplateImageJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );
        xyLabelTemplateImageJPanel1Layout.setVerticalGroup(
            xyLabelTemplateImageJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xyOLPLaunchSettingsJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xyLoadLabelTemplateJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xyOLPRecallPrintedLabelJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xyOLPStoreLabelJPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xyOffsettingJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xyPrinterControlJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
            .addComponent(xyLabelTemplateImageJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(xyOLPLaunchSettingsJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(xyLoadLabelTemplateJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(xyOLPRecallPrintedLabelJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xyOLPStoreLabelJPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xyOffsettingJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xyPrinterControlJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xyLabelTemplateImageJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.xyratex.label.apps.gui.components.XyLabelTemplateImageJPanel xyLabelTemplateImageJPanel1;
    private com.xyratex.label.apps.gui.components.XyLoadLabelTemplateJPanel xyLoadLabelTemplateJPanel1;
    private com.xyratex.label.apps.gui.components.XyOLPLaunchSettingsJPanel xyOLPLaunchSettingsJPanel1;
    private com.xyratex.label.apps.gui.components.XyOLPRecallPrintedLabelJPanel xyOLPRecallPrintedLabelJPanel1;
    private com.xyratex.label.apps.gui.components.XyOLPStoreLabelJPanel1 xyOLPStoreLabelJPanel11;
    private com.xyratex.label.apps.gui.components.XyOffsettingJPanel xyOffsettingJPanel1;
    private com.xyratex.label.apps.gui.components.XyPrinterControlJPanel xyPrinterControlJPanel1;
    // End of variables declaration//GEN-END:variables

}
