/*
 * XyPrinterControlJPanel.java
 *
 * Created on 17 November 2008, 16:05
 */

package com.xyratex.label.apps.gui.components;

import javax.swing.SpinnerListModel;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;


/**
 *
 * @author  rdavis
 */
public class XyPrinterControlJPanel extends javax.swing.JPanel {

    private static Log log = LogFactory.getLog(XyPrinterControlJPanel.class);
    
    private XyPrinterControlLogic xyPrinterControlLogic = null;
    
    /** Creates new form XyPrinterControlJPanel */
    public XyPrinterControlJPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        XyPrinterSelectionJSpinner = new javax.swing.JSpinner();
        XyResolutionSelectionJSpinner = new javax.swing.JSpinner();
        XyPrinterJLabel = new javax.swing.JLabel();
        XyResolutionJLabel = new javax.swing.JLabel();
        XyPrintJButton = new javax.swing.JButton();

        XyPrinterSelectionJSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                XyPrinterSelectionJSpinnerStateChanged(evt);
            }
        });

        XyResolutionSelectionJSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                XyResolutionSelectionJSpinnerStateChanged(evt);
            }
        });

        XyPrinterJLabel.setText("Printer");

        XyResolutionJLabel.setText("resolution");

        XyPrintJButton.setText("Print");
        XyPrintJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XyPrintJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(XyPrinterJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(XyPrinterSelectionJSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(XyResolutionJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(XyResolutionSelectionJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(XyPrintJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(XyPrinterJLabel)
                .addComponent(XyPrintJButton)
                .addComponent(XyResolutionJLabel)
                .addComponent(XyResolutionSelectionJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(XyPrinterSelectionJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setLogic( XyPrinterControlLogic logic )
    {
        xyPrinterControlLogic = logic;
        
        XyResolutionSelectionJSpinner.setModel( new SpinnerListModel( xyPrinterControlLogic.getDotsPerUnitLengthList() ) );
        XyPrinterSelectionJSpinner.setModel( new SpinnerListModel( xyPrinterControlLogic.getPrinterList() ) );
    
        String initialResolution = getJSpinnerState( XyResolutionSelectionJSpinner );
        if ( initialResolution != null )
        {
            log.trace("initial resolution = " + initialResolution );
            xyPrinterControlLogic.setResolution( initialResolution );
        }
        
        String initialPrinterSelection = getJSpinnerState( XyPrinterSelectionJSpinner );
        if ( initialPrinterSelection != null )
        {
            log.trace("initial printer selection = " + initialPrinterSelection );
            xyPrinterControlLogic.setPrinter( initialPrinterSelection );
        }
    }
    
    public String getJSpinnerState( javax.swing.JSpinner jSpinner )
    {
        String valStr = null;
        
                    Object val = ((javax.swing.JSpinner)jSpinner).getValue();
            
            if ( val instanceof String )
            {
              valStr = (String)val;
            }

            return valStr;
    }
    
private void XyPrinterSelectionJSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_XyPrinterSelectionJSpinnerStateChanged
    Object source = evt.getSource();
    if ( source instanceof javax.swing.JSpinner )
    {
        String valStr = getJSpinnerState( (javax.swing.JSpinner)source);
        
        if ( valStr != null )
        {
            log.trace( valStr );
                xyPrinterControlLogic.setPrinter( valStr );
        }
    }
}//GEN-LAST:event_XyPrinterSelectionJSpinnerStateChanged

private void XyResolutionSelectionJSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_XyResolutionSelectionJSpinnerStateChanged
    Object source = evt.getSource();
    if ( source instanceof javax.swing.JSpinner )
    {
        String valStr = getJSpinnerState( (javax.swing.JSpinner)source);
        
        if ( valStr != null )
        {
                        log.trace( valStr );
                xyPrinterControlLogic.setResolution( (String)valStr );
        }
    }
}//GEN-LAST:event_XyResolutionSelectionJSpinnerStateChanged

private void XyPrintJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XyPrintJButtonActionPerformed
xyPrinterControlLogic.print();
}//GEN-LAST:event_XyPrintJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton XyPrintJButton;
    private javax.swing.JLabel XyPrinterJLabel;
    private javax.swing.JSpinner XyPrinterSelectionJSpinner;
    private javax.swing.JLabel XyResolutionJLabel;
    private javax.swing.JSpinner XyResolutionSelectionJSpinner;
    // End of variables declaration//GEN-END:variables

}
