//-------------------------------------------------------------------------
// (C) COPYRIGHT Xyratex Storage Systems Division 2011
// All Rights Reserved
//
// Filename    : XyCompositeLabel.java
// Author      : Rob Davis


// By          : Rob Davis
// File Type   : Java source code for Open Label Print
//-------------------------------------------------------------------------

package com.xyratex.label.output.print;

/**
 * <p>A container used where the printing on a label is created from a combination of host-computer-generated
 * bitmaps and barcodes generated by the printer itself.
 * </p>
 * 
 * <p>Not currently implemented as printing on a label is created on an attached host-PC and sent
 * entirely as a bitmap to the printer</p>
 * 
 * <p>This class would be useful for two scenarios:</p>
 * <ol>
 *  <li>Where the host-PC is not fast enough at generating printing graphics for the printer.
 *  It can generate and print the image, but the time taken is longer than requirements specify.</li>
 *  <li>Where the printer supports a symbology and the host-PC does not.</li>
 * </ol>
 * 
 * <p>At current time, we expect not to use or implement this option as we expect the attached
 * host PC to be capable of generating the printer graphics and support the required symbologies.</p>
 * 
 * @author rdavis
 *
 */
public class XyCompositeLabel
{
	/**
	 *  R = Release L = Level G = date U = time
	 *  Values calculated by SCCS when file is checked out and compiled.
	 */
	public static final String sccsid = "@(#)Xyratex  ISTP  XyCompositeLabel.java  %R%.%L%, %G% %U%";
	
	/**
	 * Not implemented yet. See above.
	 */
  public void addBarcode()
  {
  	
  }
  
	/**
	 * Not implemented yet. See above.
	 */
  public void addBitmap()
  {
  	
  }
}
