//-------------------------------------------------------------------------
// (C) COPYRIGHT Xyratex Storage Systems Division 2011
// All Rights Reserved
//
// Filename    : XyLabelPrintService.java
// Author      : Rob Davis


// By          : Rob Davis
// File Type   : Java source code for Open Label Print
//-------------------------------------------------------------------------

package com.xyratex.label.output.print;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;

import javax.print.PrintException;

/**
 * <p>This is the interface to be used by a program that creates graphics for printing.
 * The program would call methods on this interface appropriate to the kind of graphics.
 * For example for bitmaps, there is a printBitmap method.
 * </p>
 * <p> However, this interface could be extended to support other graphics types, particularly 
 * requests to the printer to generate symbols such as barcodes itself. Such on-board-printer 
 * features are printer model specific but this interface would hide the specifics by providing
 * common abstractions in the form of interfaces, e.g. a barcode object.
 * </p>
 * 
 * @author rdavis
 *
 */
public interface XyLabelPrintService
{
	/**
	 *  R = Release L = Level G = date U = time
	 *  Values calculated by SCCS when file is checked out and compiled.
	 */
	public static final String sccsid = "@(#)Xyratex  ISTP  XyLabelPrintService.java  %R%.%L%, %G% %U%";

	/**
	 * Get the full name of the printer as a String.
	 */
	public String getPrinterName();
 
	/**
	 * Print the bitmap from a .png File
	 */
	public void printBitmap( File png ) throws Exception;
	
	/**
	 * Output to a file the printer command sequence for the bitmap printing.
	 * 
	 * Use this function for testing and analysis purposes and also to
	 * print Open Label Print-generated bitmap images without the need to
	 * install OLP - e.g. for trying out new trial loaned printersS.
	 * 
	 */
	public void printToFileBitmap( final File png, File output ) throws PrintException, IOException;
  
	
	/**
	 * Print the bitmap from an InputStream.
	 */
	public void printBitmap( InputStream is ) throws IOException, PrintException;
	
  /**
   * <p>Not implemented yet. This will provide the ability to print the label bitmap together with
   * Variable fields such as barcodes generated by the printer itself. It is an alternative
   * option for generating labels if the host computer is not fast enough to generate barcodes in
   * the label image or if the printer supports the barcode but the host generating software does not.</p>
   */
	public void printComposite( XyCompositeLabel composite )  throws Exception;
	
	public void addListener( XyPrinterResponseListener listener );
	
	/**
	 * <p>Set the darkness of the image printed. Very dark images tend to bleed and thin
	 * gaps disappear but the benefit is smoother curved edges on logos and symbols.</p>
	 *
	 * <p>Expressed as a string because this is the most flexible and universal representation
	 * of values. The actual implementations of this interface can convert it to the
	 * printer specific representation.</p>
	 * 
	 * @param darkness - the darkness
	 */
	public void setDarkness( String darkness );
	
	/**
	 * <p>Set the origin, to position the printing on the label</p>
	 * 
	 * <p>Expressed as a string because this is the most flexible and universal representation
	 * of values. The actual implementations of this interface can convert it to the
	 * printer specific implementation.</p>
	 *
	 * <p>The origin value may contain values for x and y as we expect that these can only be
	 * set together and not separately on printer specific implementations.</p>
	 * 
	 * @param origin
	 */

	public void setOrigin( String origin );
}
